name: Dusk Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  dusk:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: xptrackr_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysql, pdo_mysql, bcmath, intl, gd

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Copy .env.dusk.local
      run: cp .env .env.dusk.local

    - name: Update .env.dusk.local
      run: |
        sed -i "s/DB_DATABASE=.*/DB_DATABASE=xptrackr_test/" .env.dusk.local
        sed -i "s/DB_HOST=.*/DB_HOST=127.0.0.1/" .env.dusk.local
        sed -i "s/DB_USERNAME=.*/DB_USERNAME=root/" .env.dusk.local
        sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=password/" .env.dusk.local

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install NPM dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: xptrackr_test
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan migrate --force

    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver --detect

    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux &

    - name: Start Laravel Server
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: xptrackr_test
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan serve --no-reload &

    - name: Run Dusk Tests
      env:
        APP_URL: "http://127.0.0.1:8000"
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: xptrackr_test
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan dusk

    - name: Upload Screenshots
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: tests/Browser/screenshots

    - name: Upload Console Logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: console
        path: tests/Browser/console
